import sys
sys.path.insert(0, './src')
from app.utils.db_connection import query

rows = query("SELECT DT_REFERENCIA, VL_COTA, QT_COTAS, VL_FLUXO_LIQ_DIA FROM (SELECT c.DT_REFERENCIA, c.VL_COTA, c.QT_COTAS, (SELECT SUM(CASE WHEN f.TP_FLUXO = 'APORTE' THEN f.VL_FLUXO ELSE -f.VL_FLUXO END) FROM FAT_FUNDO_FLUXO_CAPITAL f WHERE f.ID_FUNDO=c.ID_FUNDO AND f.DT_REFERENCIA=c.DT_REFERENCIA) AS VL_FLUXO_LIQ_DIA FROM FAT_FUNDO_COTA_DIARIA c WHERE c.ID_FUNDO=18 AND c.DT_REFERENCIA <= '2025-03-05' ORDER BY c.DT_REFERENCIA)")
for r in rows.to_dict('records'):
    print(f"{r['DT_REFERENCIA']} | COTA: {r['VL_COTA']:.4f} | QT: {r['QT_COTAS']:.2f} | FLUXO: {r['VL_FLUXO_LIQ_DIA'] or 0:.2f}")

