-- Script para migrar tabelas de public para mercado
-- Execute este script no PostgreSQL para o banco eletrofundo

-- ============================================
-- 1. CRIAR TABELAS NO SCHEMA MERCADO
-- ============================================

-- Tabela tipoativo
CREATE TABLE mercado.tipoativo (
    idtipoativo INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR(255)
);

-- Tabela ativos (simplificada, removendo IDs desnecessários)
CREATE TABLE mercado.ativos (
    idativo INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(55) UNIQUE NOT NULL,           -- Alias: NVDA, PETR4
    ticker_yf VARCHAR(55) UNIQUE NOT NULL,        -- Yahoo Finance: NVDA, PETR4.SA
    idtipoativo INT REFERENCES mercado.tipoativo(idtipoativo),
    moeda VARCHAR(10) DEFAULT 'BRL',
    created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- 2. COPIAR DADOS DE PUBLIC PARA MERCADO
-- ============================================

-- Copiar tipoativo
INSERT INTO mercado.tipoativo (idtipoativo, descricao)
SELECT idtipoativo, descricao FROM public.tipoativo
ON CONFLICT (idtipoativo) DO NOTHING;

-- Copiar ativos (apenas campos necessários)
INSERT INTO mercado.ativos (idativo, codigo, ticker_yf, idtipoativo, moeda)
SELECT 
    idativo,
    codigo,
    ticker_yf,
    idtipoativo,
    moeda
FROM public.ativos
ON CONFLICT (idativo) DO NOTHING;

-- ============================================
-- 3. CRIAR ÍNDICES
-- ============================================

CREATE INDEX idx_ativos_codigo ON mercado.ativos(codigo);
CREATE INDEX idx_ativos_ticker_yf ON mercado.ativos(ticker_yf);
CREATE INDEX idx_ativos_tipoativo ON mercado.ativos(idtipoativo);

-- ============================================
-- 4. CRIAR TABELAS RELACIONADAS
-- ============================================

-- Tabela de preços históricos
CREATE TABLE mercado.precos_historicos (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idativo INT REFERENCES mercado.ativos(idativo) ON DELETE CASCADE,
    data DATE NOT NULL,
    preco_moeda_local NUMERIC(10, 4),
    preco_real NUMERIC(10, 4),
    volume BIGINT,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(idativo, data)
);

CREATE INDEX idx_precos_ativo_data ON mercado.precos_historicos(idativo, data);

-- Tabela de taxa de câmbio
CREATE TABLE mercado.taxa_cambio (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data DATE UNIQUE,
    usd_brl NUMERIC(10, 4),
    criado_em TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- 5. VERIFICAÇÃO
-- ============================================

-- Verificar quantidade de registros
SELECT 'tipoativo' as tabela, COUNT(*) as total FROM mercado.tipoativo
UNION ALL
SELECT 'ativos', COUNT(*) FROM mercado.ativos;

-- Visualizar algumas linhas
SELECT * FROM mercado.tipoativo LIMIT 5;
SELECT * FROM mercado.ativos LIMIT 5;
